development:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  session_token: <%= ENV['AWS_SESSION_TOKEN'] %>
  region: us-east-1

test:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  session_token: <%= ENV['AWS_SESSION_TOKEN'] %>
  region: us-east-1

production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  session_token: <%= ENV['AWS_SESSION_TOKEN'] %>
  region: us-east-1
